name: pnu_plato_advanced_browser
description: Pnu Plato Advanced Browser
version: 0.1.0+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  dio: ^4.0.4
  html: ^0.15.0
  flutter_inappwebview: ^5.3.2
  flutter_expanded_tile: ^0.3.6
  table_calendar: ^3.0.3
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  marquee: ^2.2.0
  cached_network_image: ^3.2.0
  http: ^0.13.4
  flutter_cache_manager: ^3.3.0
  open_file: ^3.2.1
  fluttertoast: ^8.0.8
  path_provider: ^2.0.8
  permission_handler: ^9.2.0
  badges: ^2.0.2
  flutter_svg: ^1.0.3
  restart_app: ^1.1.0
  flutter_background_service: ^1.0.4
  url_launcher: ^6.0.20
  flutter_treeview: ^1.0.7+1
  disable_battery_optimization: ^1.1.0+1
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  flutter_widget_from_html: ^0.8.5
  awesome_notifications: ^0.6.21
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1
  watcher: ^1.0.1
  mailer: ^5.1.0
  flutter_launcher_icons: ^0.9.2
  better_player:
    git:
      url: https://github.com/shiyiya/betterplayer
      ref: master

dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master

dev_dependencies:
  build_runner: ^2.1.8
  objectbox_generator: ^1.4.1
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/landingImages/

  fonts:
    - family: NaNumSquearRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundB.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/ios_icon.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"